const TRACK_NEXT = 'TRACK/NEXT';
const TRACK_PREV = 'TRACK/PREV';
const TRACK_NEXT_IN_SEQUENCE = 'TRACK/TRACK_NEXT_IN_SEQUENCE';
const MODE_RANDOM = 'MODE/RANDOM';
const MODE_LOOP = 'MODE/LOOP';

export {
  TRACK_NEXT, TRACK_PREV, TRACK_NEXT_IN_SEQUENCE, MODE_RANDOM, MODE_LOOP,
};
